# Generated by Django 3.2 on 2022-05-24 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('128acda4-1152-4ac3-bf5e-9edfeda87e8d')),
        ),
    ]
