# Generated by Django 3.2 on 2022-05-24 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5643ac71-36d8-446a-9972-2f6ca21932f7')),
        ),
    ]
