# Generated by Django 3.2 on 2022-05-24 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63e58806-8abf-4a31-8e67-130865d165fc')),
        ),
    ]
