# Generated by Django 3.2 on 2022-05-24 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7b744708-f3a9-4ef1-b371-eed4297c01e5')),
        ),
    ]
