# Generated by Django 3.2 on 2022-05-25 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2aeb4d15-fd2f-4a49-9edc-0e86d9472634')),
        ),
    ]
