# Generated by Django 3.2 on 2022-05-25 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b0e6f9be-ffdb-4e11-8bd3-d9cffd2a9490')),
        ),
    ]
