# Generated by Django 3.2 on 2022-05-25 02:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('68d2f6cd-d48d-490b-9d32-730ce737d5fd')),
        ),
    ]
